title: Sharewise App
description: Free online expense splitter and bill tracker
url: https://darshanleads09.github.io
baseurl: /sharewise-app
author: Sharewise
email: contact@sharewise.app
plugins:
  - jekyll-sitemap
  - jekyll-feed
markdown: kramdown
theme: jekyll-theme-cayman
